CREATE USER KOSTAMOVIE IDENTIFIED BY KOSTAMOVIE;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO KOSTAMOVIE;





--유저 등급 테이블
CREATE TABLE USER_ROLE(
    U_ID NUMBER(10) PRIMARY KEY, --등급고유번호
    ROLE_NAME VARCHAR2(12 CHAR) NOT NULL, --등급이름
    REQ_POINT INT DEFAULT 0 NOT NULL,--필요포인트
    ROLE_PRIORITY INT NOT NULL--등급우선순위
);
DROP SEQUENCE  URID_SEQ;
CREATE SEQUENCE URID_SEQ NOCACHE;

INSERT INTO USER_ROLE values(0, '일반 회원', 0, 0);
INSERT INTO USER_ROLE values(URID_SEQ.NEXTVAL, '정회원', 10, URID_SEQ.CURRVAL);
INSERT INTO USER_ROLE values(URID_SEQ.NEXTVAL, '우수 회원', 20, URID_SEQ.CURRVAL);


--유저 테이블
CREATE TABLE USERLIST(
    U_ID INT PRIMARY KEY,  --고유유저번호 (카카오 고유 아이디 번호)
    ROLE_ID NUMBER(10) DEFAULT 0 NOT NULL REFERENCES USER_ROLE(U_ID) ON DELETE CASCADE, --등급고유번호
    NICKNAME VARCHAR2(15) NOT NULL ,--닉네임
    EMAIL VARCHAR2(255) NOT NULL, --유저 EMAL
    CREATED_IP VARCHAR2(255) NOT NULL, --유저 IP
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL, --가입일
    ACCOUNT_LOCKED NUMBER(1) DEFAULT 0 NOT NULL, --IP벤 유무
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL, --마지막 접속일
    LAST_UPDATE_IP VARCHAR2(255) NOT NULL, --마지막 접속 IP  
    POINTS INT DEFAULT 0 NOT NULL,--POINT
    VIEW_ADULT NUMBER(1) DEFAULT 0 NOT NULL, --성인열람
    AGE_ADULT NUMBER(1) DEFAULT 0 NOT NULL --성인 나이 여부
);

--관리자 테이블
CREATE TABLE USER_ADMIN(
    U_ID INT PRIMARY KEY, --고유번호
    USER_UID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE --유저 고유 번호
);
DROP SEQUENCE  AID_SEQ;
CREATE SEQUENCE AID_SEQ NOCACHE;


--파일 테이블
CREATE TABLE UPLOAD_FILE(
    U_ID INT PRIMARY KEY,  --파일번호
    USER_UID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE, --업로더 고유아이디
    FILE_NAME VARCHAR2(128) NOT NULL,--파일면
    FILE_SIZE NUMBER(10) NOT NULL,--파일 BYTE 크기
    FILE_TYPE VARCHAR2(128) NOT NULL, --파일 형식
    UPLOAD_DATE DATE DEFAULT SYSDATE,--업로드일
    IMG_HEIGHT NUMBER(6) DEFAULT 0,--이미지 높이
    IMG_WIDTH NUMBER(6) DEFAULT 0--이미지 넓이
);
DROP SEQUENCE FID_SEQ;
CREATE SEQUENCE FID_SEQ NOCACHE;

--포인트 샵 테이블
CREATE TABLE POINT_SHOP(
    U_ID NUMBER(20) PRIMARY KEY,--아이템 고유번호
    ITEM_NAME VARCHAR2(255) NOT NULL,--아이템이름
    ITEM_TYPE VARCHAR2(255) NOT NULL,--아이템종류
    ITEM_POINT INT NOT NULL,--요구 포인트
    ITEM_STOCK INT NOT NULL,--아이템 수량
    ITEM_LOCKED NUMBER(1) DEFAULT 0,--아이템잠금여부
    FILE_ID NUMBER(10) REFERENCES UPLOAD_FILE(U_ID) ON DELETE CASCADE, --파일번호
    REQ_ROLE_ID NUMBER(10) REFERENCES USER_ROLE(U_ID) ON DELETE CASCADE--등급고유번호
);
DROP SEQUENCE  PID_SEQ;
CREATE SEQUENCE PID_SEQ NOCACHE;


--게시글 업로드 테이블
CREATE TABLE FORUM_UPLOAD(
    U_ID INT PRIMARY KEY, --고유번호
    THREAD_ID INT REFERENCES FORUM_THREAD(U_ID) ON DELETE CASCADE, --글번호
    FILE_ID INT REFERENCES UPLOADFILE(U_ID) ON DELETE CASCADE--파일번호
);
DROP SEQUENCE  FU_ID_SEQ;
CREATE SEQUENCE FU_ID_SEQ NOCACHE;


--글 카테고리 테이블
CREATE TABLE FORUM_CATEGORY(
    U_ID INT PRIMARY KEY, --카테고리 번호
    REQ_READ NUMBER(10) REFERENCES USER_ROLE(U_ID) ON DELETE CASCADE, --읽기 권한 요구 등급
    REQ_WRITE NUMBER(10) REFERENCES USER_ROLE(U_ID) ON DELETE CASCADE,--쓰기 권한 요구 등급
    GUEST VARCHAR2(1) DEFAULT 0 --손님 보기 허용 여부
);
DROP SEQUENCE  FCID_SEQ;
CREATE SEQUENCE FCID_SEQ NOCACHE;


--게시글 테이블
CREATE TABLE FORUM_THREAD(
    U_ID INT PRIMARY KEY, --글번호
    FORUM_CATEGORY_ID INT REFERENCES FORUM_CATEGORY(U_ID),
    COUNT_READ INT DEFAULT 0, --읽은횟수
    COUNT_POST INT DEFAULT 0, --댓글수
    AUTHOR_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE, --작성자 고유아이디
    THREAD_LOCKED NUMBER(1) DEFAULT 0,--글 잠금여부
    POST_LOCKED NUMBER(1) DEFAULT 0, --댓글 잠금여부
    VOTE INT DEFAULT 0,--찬성/반대 점수
    TEXT VARCHAR2(512) NOT NULL, --글 내용
    TITLE VARCHAR2(2128) NOT NULL,--글 제목
    TIMEDATE DATE DEFAULT SYSDATE   --날짜
);
DROP SEQUENCE  FTID_SEQ;
CREATE SEQUENCE FTID_SEQ NOCACHE;


--공지 테이블
CREATE TABLE FORUM_NOTICE(
    U_ID INT PRIMARY KEY, --고유번호
    THREAD_ID INT  REFERENCES FORUM_THREAD(U_ID) ON DELETE CASCADE, --글번호
    ALL_FORUM NUMBER(1) DEFAULT 0 --전체공지 (0/1)
);
DROP SEQUENCE  FNID_SEQ;
CREATE SEQUENCE FNID_SEQ NOCACHE;


--댓글 테이블
CREATE TABLE FORUM_POST(
    U_ID INT PRIMARY KEY, --댓글번호
    TEXT VARCHAR2(512) NOT NULL,--댓글내용
    THREAD_ID INT REFERENCES FORUM_THREAD(U_ID) ON DELETE CASCADE,--글번호
    AUTHOR_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE,--댓글작성자 고유아이디
    VOTE INT DEFAULT 0, --찬성/반대 점수
    TIMEDATE DATE DEFAULT SYSDATE--날자
);
DROP SEQUENCE  FPID_SEQ;
CREATE SEQUENCE FPID_SEQ NOCACHE;

--영화 리뷰 테이블
CREATE TABLE FORUM_REVIEW(
    U_ID INT PRIMARY KEY, --고유번호
    THREAD_ID INT REFERENCES FORUM_THREAD(U_ID) ON DELETE CASCADE, --글번호
    MOVIE_ID INT,--영화 고유 아이디
    RATE NUMBER(4) DEFAULT 0.5 --평점
);
DROP SEQUENCE  FRID_SEQ;
CREATE SEQUENCE FRID_SEQ NOCACHE;

--찬성/반대 테이블
CREATE TABLE FORUM_VOTE(
 U_ID INT PRIMARY KEY, --고유번호
 USER_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE,--유저고유아이디
 CONTENT_ID INT,--참조 글번호
 FORUM_TYPE NUMBER(5) DEFAULT 0,--참조 글 타입(1 :글  2:댓글)
 FORUM_VOTE NUMBER(1) DEFAULT 0,-- 0:중립(취소) 1 :찬성  -1 : 반대
 TIMEDATE DATE DEFAULT SYSDATE --날짜
);
DROP SEQUENCE  FVID_SEQ;
CREATE SEQUENCE FVID_SEQ NOCACHE;


-- 알람 테이블
CREATE TABLE NOTIFICATION(
    U_ID INT PRIMARY KEY,--고유번호
    SENDER_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE, --송신자 고유 아이디
    RECEIVER_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE,--수신자 고유 아이디
    CONTENT_ID INT NOT NULL,--참조 글번호
    CONTENT_TYPE NUMBER(5) DEFAULT 0, --참조 글 타입(0 :쪽지  1: 글  2:댓글 )
    TIMEDATE DATE DEFAULT SYSDATE, --날짜
    CHECKED NUMBER(1) DEFAULT 0 --알람여부
);
DROP SEQUENCE NID_SEQ;
CREATE SEQUENCE NID_SEQ NOCACHE;


-- 쪽지 테이블
CREATE TABLE USER_LETTER(
    U_ID INT PRIMARY KEY,--고유번호
    SENDER_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE, --송신자 고유 아이디
    RECEIVER_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE,--수신자 고유 아이디
    TEXT VARCHAR2(512) NOT NULL,--쪽지 내용
    TIMEDATE DATE DEFAULT SYSDATE, --날짜
    CHECKED NUMBER(1) DEFAULT 0 --알람여부
);
DROP SEQUENCE NID_SEQ;
CREATE SEQUENCE NID_SEQ NOCACHE;


-- 즐겨찾기 테이블
CREATE TABLE MOVIE_USER_FAVORITE(
    U_ID INT PRIMARY KEY, --고유번호
    USER_ID INT REFERENCES USERLIST(U_ID) ON DELETE CASCADE, --유저 고유 아이디
    MOVIE_ID NUMBER(10) NOT NULL,--영화 고유 아이디
    ADD_DATE DATE DEFAULT SYSDATE,--추가 날짜
    WATCH NUMBER(1) DEFAULT 0--관람 여부
);
DROP SEQUENCE MUFID_SEQ;
CREATE SEQUENCE MUFID_SEQ NOCACHE;









